--[[ 
    LOADER GENERATED BY PYTHON
    Target: Protected
]]

local CONFIG = {
    Title = "Photios HUB | Key System",
    KeyURL = "https://raw.githubusercontent.com/nonamemansd/robloxscripts/refs/heads/main/main.txt",
    ScriptURL = "https://pastefy.app/Oqh2C1eX/raw",
    Linkvertise = "https://work.ink/1ZVP/key",
    FileName = "PhotiosKey.data" -- Имя файла для сохранения ключа
}

local CoreGui = game:GetService("CoreGui")
local HttpService = game:GetService("HttpService")

-- >> ФУНКЦИИ СИСТЕМЫ СОХРАНЕНИЯ << --
local function GetSavedKey()
    if isfile(CONFIG.FileName) then
        return readfile(CONFIG.FileName)
    end
    return ""
end

local function SaveKey(key)
    writefile(CONFIG.FileName, key)
end

-- >> ПРОВЕРКА КЛЮЧА ПРИ ЗАПУСКЕ << --
local function CheckAndLoad()
    local success, onlineKey = pcall(function() return game:HttpGet(CONFIG.KeyURL) end)
    if not success then return false end
    
    onlineKey = onlineKey:gsub("%s+", "") -- Убираем пробелы
    local savedKey = GetSavedKey():gsub("%s+", "")
    
    if savedKey == onlineKey and onlineKey ~= "" then
        return true -- Ключ совпадает, загружаем
    end
    return false, onlineKey -- Ключ не совпадает, возвращаем правильный для сверки
end

-- Если ключ уже введен верно ранее - грузим скрипт и не показываем GUI
local isAuth, trueKey = CheckAndLoad()
if isAuth then
    loadstring(game:HttpGet(CONFIG.ScriptURL))()
    return
end

-- >> UI ИНТЕРФЕЙС << --
if CoreGui:FindFirstChild("KeySystemUI") then CoreGui.KeySystemUI:Destroy() end

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "KeySystemUI"
ScreenGui.Parent = CoreGui
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainFrame"
MainFrame.Parent = ScreenGui
MainFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
MainFrame.Position = UDim2.new(0.5, -150, 0.5, -90)
MainFrame.Size = UDim2.new(0, 300, 0, 180)
MainFrame.Active = true
MainFrame.Draggable = true

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 8)
UICorner.Parent = MainFrame

local Title = Instance.new("TextLabel")
Title.Parent = MainFrame
Title.BackgroundTransparency = 1
Title.Position = UDim2.new(0, 0, 0, 10)
Title.Size = UDim2.new(1, 0, 0, 20)
Title.Font = Enum.Font.GothamBold
Title.Text = CONFIG.Title
Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Title.TextSize = 16

local KeyInput = Instance.new("TextBox")
KeyInput.Parent = MainFrame
KeyInput.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
KeyInput.Position = UDim2.new(0.1, 0, 0.25, 0)
KeyInput.Size = UDim2.new(0.8, 0, 0, 40)
KeyInput.Font = Enum.Font.Gotham
KeyInput.PlaceholderText = "Enter Key..."
KeyInput.Text = ""
KeyInput.TextColor3 = Color3.fromRGB(255, 255, 255)
KeyInput.TextSize = 14
KeyInput.TextXAlignment = Enum.TextXAlignment.Center

local UICornerInput = Instance.new("UICorner")
UICornerInput.CornerRadius = UDim.new(0, 6)
UICornerInput.Parent = KeyInput

local GetKeyBtn = Instance.new("TextButton")
GetKeyBtn.Parent = MainFrame
GetKeyBtn.BackgroundColor3 = Color3.fromRGB(0, 100, 200)
GetKeyBtn.Position = UDim2.new(0.1, 0, 0.6, 0)
GetKeyBtn.Size = UDim2.new(0.38, 0, 0, 35)
GetKeyBtn.Font = Enum.Font.GothamBold
GetKeyBtn.Text = "Get Key"
GetKeyBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
GetKeyBtn.TextSize = 12

local UICornerBtn1 = Instance.new("UICorner")
UICornerBtn1.CornerRadius = UDim.new(0, 6)
UICornerBtn1.Parent = GetKeyBtn

local CheckBtn = Instance.new("TextButton")
CheckBtn.Parent = MainFrame
CheckBtn.BackgroundColor3 = Color3.fromRGB(0, 160, 0)
CheckBtn.Position = UDim2.new(0.52, 0, 0.6, 0)
CheckBtn.Size = UDim2.new(0.38, 0, 0, 35)
CheckBtn.Font = Enum.Font.GothamBold
CheckBtn.Text = "Check Key"
CheckBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
CheckBtn.TextSize = 12

local UICornerBtn2 = Instance.new("UICorner")
UICornerBtn2.CornerRadius = UDim.new(0, 6)
UICornerBtn2.Parent = CheckBtn

local Status = Instance.new("TextLabel")
Status.Parent = MainFrame
Status.BackgroundTransparency = 1
Status.Position = UDim2.new(0, 0, 0.85, 0)
Status.Size = UDim2.new(1, 0, 0, 20)
Status.Font = Enum.Font.Gotham
Status.Text = "Status: Waiting..."
Status.TextColor3 = Color3.fromRGB(150, 150, 150)
Status.TextSize = 12

-- >> ЛОГИКА КНОПОК << --
GetKeyBtn.MouseButton1Click:Connect(function()
    if setclipboard then
        setclipboard(CONFIG.Linkvertise)
        GetKeyBtn.Text = "Copied to Clipboard!"
        task.wait(1.5)
        GetKeyBtn.Text = "Get Key"
    end
end)

CheckBtn.MouseButton1Click:Connect(function()
    Status.Text = "Checking..."
    local entered = KeyInput.Text:gsub("%s+", "")
    
    local success, keyOnline = pcall(function() return game:HttpGet(CONFIG.KeyURL) end)
    
    if success then
        keyOnline = keyOnline:gsub("%s+", "")
        if entered == keyOnline then
            Status.Text = "Correct! Loading..."
            Status.TextColor3 = Color3.fromRGB(0, 255, 0)
            SaveKey(entered) -- СОХРАНЯЕМ КЛЮЧ
            task.wait(1)
            ScreenGui:Destroy()
            loadstring(game:HttpGet(CONFIG.ScriptURL))()
        else
            Status.Text = "Incorrect Key!"
            Status.TextColor3 = Color3.fromRGB(255, 0, 0)
            task.wait(1)
            Status.Text = "Status: Waiting..."
            Status.TextColor3 = Color3.fromRGB(150, 150, 150)
        end
    else
        Status.Text = "HTTP Error (Check Internet)"
    end
end)
